### ISSUE TITLE
Pending task for new process of releasing with golang migration

### ISSUE THREAD

**Issue by subhamkrai** [rook/kubectl-rook-ceph#125]
These are steps we need to do for releasing with go
 

- [x] Clean the project by removing bash content. Fixes: #127
- [x] Add [goreleaser](https://goreleaser.com/) for releasing the binary in all the possible supported formats. It will help in releasing binary in different os with different architecture.  Fixes: #126 
- [x] update `.krew.yaml` to reflect the golang binary with the right version. Fixes: #128  ( prnot ready for review)
- [x] Finally, before releasing do the testing, by going inside goreleaser ci runner and confirming the binary is working as expected.

**Comment by subhamkrai** [comment]
@travisn I created the issue so that we are all on the same page regarding adding the changes for the new release

**Comment by travisn** [comment]
When someone upgrades the krew plugin, will the bash script be automatically removed? Or is there any manual cleanup?

**Comment by subhamkrai** [comment]
> When someone upgrades the krew plugin, will the bash script be automatically removed? Or is there any manual cleanup?

I assumption is krew should handle that automatically.

**Comment by travisn** [comment]
> > When someone upgrades the krew plugin, will the bash script be automatically removed? Or is there any manual cleanup?
> 
> I assumption is krew should handle that automatically.

Is there a way to test the new release before it's officially out? Then we can confirm that the upgrade is smooth for the transition.

**Comment by travisn** [comment]
btw let's wait until early next week for the release so we don't have a release just before the weekend

**Comment by subhamkrai** [comment]
> btw let's wait until early next week for the release so we don't have a release just before the weekend

Yes, I have a few testing with migration to do I have found this https://krew.sigs.k8s.io/docs/developer-guide/testing-locally/ to test locally exploring how we can test this.

**Comment by subhamkrai** [comment]
also holding this pr https://github.com/rook/kubectl-rook-ceph/pull/128 till above testing is done

**Comment by subhamkrai** [comment]
> > btw let's wait until early next week for the release so we don't have a release just before the weekend
> 
> Yes, I have a few testing with migration to do I have found this https://krew.sigs.k8s.io/docs/developer-guide/testing-locally/ to test locally exploring how we can test this.

I did manual testing it was working but the testing process is not the same as the one we have in CI, since ci is full automation and one ci depends on another CI.   We can follow up offline

**Comment by subhamkrai** [comment]
All task is done.
